In [1]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000222EBDAB0E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/sklearn/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000222EBD83890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/sklearn/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000222EBD839D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/sklearn/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000222EBD83B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/sklearn/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000222EBD83C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/sklearn/
ERROR: Could not find a version that satisfies the requirement sklearn (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for sklearn

In [1]:
import numpy as np
import pandas as pd

In [3]:
telco = pd.read_csv("Telco-Customer-Churn.csv")
telco.shape

(7043, 21)

In [4]:
telco.sample()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3918,6319-IEJWJ,Male,0,Yes,Yes,20,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,90.2,1776.55,Yes

In [5]:
telco.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
telco[telco.TotalCharges.isna()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [ ]:
#telco['TotalCharges'] = pd.to_numeric(telco['TotalCharges'],errors = 'coerce')

In [7]:
telco.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [8]:
telco.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
counts = telco.Churn.value_counts()
percentage = telco.Churn.value_counts(normalize = True)*100

result = pd.concat([counts,percentage],axis=1,keys=['Count','Percentage'])
print(result)

       Count  Percentage
Churn
No      5174   73.463013
Yes     1869   26.536987

In [10]:
telco['SeniorCitizen'] = telco['SeniorCitizen'].astype(str)

In [11]:
telco['customerID'] = telco['customerID'].astype(object)

In [12]:
telco.dtypes

customerID           object
gender                  str
SeniorCitizen           str
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [ ]:

#obj_cols = telco.select_dtypes(include='str').columns
#telco[obj_cols] = telco[obj_cols].astype('category')

In [13]:
result = telco.loc[telco['Contract'] == 'Month-to-month',['MonthlyCharges','TotalCharges','Churn']]
print(result)

      MonthlyCharges TotalCharges Churn
0              29.85        29.85    No
2              53.85       108.15   Yes
4              70.70       151.65   Yes
5              99.65        820.5   Yes
6              89.10       1949.4    No
...              ...          ...   ...
7033           69.50      2625.25    No
7034          102.95      6886.25   Yes
7035           78.70       1495.1    No
7040           29.60       346.45    No
7041           74.40        306.6   Yes

[3875 rows x 3 columns]

In [ ]:
pip install scikit-learn

^C
Note: you may need to restart the kernel to use updated packages.

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,confusion_matrix,roc_auc_score

In [15]:

##TotalCharges sometimes has blank strings - clean it,
telco['TotalCharges'] = pd.to_numeric(telco['TotalCharges'],errors='coerce')
telco = telco.dropna(subset=['TotalCharges'])

In [16]:
telco = telco.drop(columns=['customerID'])

In [17]:
#Encode Target
telco.columns = telco.columns.str.strip()
telco['Churn'] = telco['Churn'].map({'Yes': 1,'No': 0})
telco_encoded = pd.get_dummies(telco, drop_first=True)

In [18]:
print(telco_encoded.columns.tolist())

['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn', 'gender_Male', 'SeniorCitizen_1', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [ ]:
#telco_encoded = telco_encoded.dropna(subset=['Churn'])

KeyError: ['Churn']

In [ ]:
#print(Y.isna().sum())

NameError: name 'Y' is not defined

In [20]:

print(telco['Churn'].unique())

[0 1]

In [21]:
#Split features and Targets
X = telco_encoded.drop(['Churn','customerID'],axis=1,errors='ignore')
Y = telco_encoded['Churn']

X_train,X_test,Y_train,Y_test = train_test_split(
    X,Y,test_size=0.2,random_state=42,stratify=Y
)

In [22]:
#Trainthemodel
model = LogisticRegression(max_iter=1000)
model.fit(X_train,Y_train)

c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [23]:
#Evaluate
Y_pred = model.predict(X_test)
Y_proba = model.predict_proba(X_test)[:,1]

print(classification_report(Y_test,Y_pred))
print("ROC-AUC:",roc_auc_score(Y_test,Y_proba))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.56      0.60       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.73      1407
weighted avg       0.79      0.80      0.80      1407

ROC-AUC: 0.836692619492574

In [24]:
#See which features matter most
coefs = pd.Series(model.coef_[0],index=X.columns).sort_values()
print(coefs.head(10)) #strongest churn-reducing features
print(coefs.tail(10)) #strongest churn-driving features

Contract_Two year                      -1.310975
Contract_One year                      -0.723810
OnlineSecurity_Yes                     -0.463434
PhoneService_Yes                       -0.452279
TechSupport_Yes                        -0.424077
Dependents_Yes                         -0.231251
OnlineBackup_Yes                       -0.218870
OnlineSecurity_No internet service     -0.104523
DeviceProtection_No internet service   -0.104523
TechSupport_No internet service        -0.104523
dtype: float64
PaymentMethod_Credit card (automatic)    0.036158
PaymentMethod_Mailed check               0.062095
StreamingMovies_Yes                      0.165744
StreamingTV_Yes                          0.194259
SeniorCitizen_1                          0.199132
MultipleLines_No phone service           0.252341
MultipleLines_Yes                        0.274962
PaperlessBilling_Yes                     0.299279
PaymentMethod_Electronic check           0.376310
InternetService_Fiber optic              0.664939
dtype: float64

In [25]:
model = LogisticRegression(max_iter=1000,class_weight='balanced')
model.fit(X_train, Y_train)

c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', max_iter=1000)

In [26]:
Y_pred_adjusted = (Y_proba >= 0.35).astype(int)
print(classification_report(Y_test,Y_pred_adjusted))

              precision    recall  f1-score   support

           0       0.88      0.78      0.83      1033
           1       0.54      0.72      0.62       374

    accuracy                           0.76      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.76      0.77      1407

In [30]:
df_original = pd.read_csv('Telco-Customer-Churn.csv')
df_original['TotalCharges'] = pd.to_numeric(df_original['TotalCharges'],errors='coerce')
df_original = df_original.dropna(subset=['TotalCharges'])

In [35]:


results = pd.DataFrame({
    'customerID' : df_original.loc[X_test.index,'customerID'] if 'customerID' in df_original.columns else X_test.index,
    'Contract' : df_original.loc[X_test.index,'Contract'],
    'InternetService' : df_original.loc[X_test.index,'InternetService'],
    'PaymentMethod' : df_original.loc[X_test.index,'PaymentMethod'],
    'tenure' : df_original.loc[X_test.index,'tenure'],
    'Churn_Probability': Y_proba
})

In [36]:
results.to_csv('churn_scores.csv', index= False)